'use strict';

const productsArr = [
  {
    id: 1,
    watch: './img/P_Versa_Pink.png',
    secondStyle: './img/P_Versa_Grey.png',
    thirdStyle: './img/P_Versa_Black.png',
    animation: 'initial-animation',
    firstColor: 'content__change-color-btn-first-versa',
    secondColor: 'content__change-color-btn-second-versa',
    thirdColor: 'content__change-color-btn-third-versa',
    name: 'fitbit versa',
    priceEuro: 179,
    priceCents: 95,
    information: '',
  },
  {
    id: 2,
    watch: './img/P_Charge3_Lilac.png',
    secondStyle: './img/P_Charge3_Black.png',
    thirdStyle: './img/P_Charge3_Blue.png',
    animation: null,
    firstColor: 'content__change-color-btn-first-charge3',
    secondColor: 'content__change-color-btn-second-charge3',
    thirdColor: 'content__change-color-btn-third-charge3',
    name: 'fitbit charge 3',
    priceEuro: 149,
    priceCents: 95,
    information: 'No todos los productos mostrados participant en ta oferta',
  },
  {
    id: 3,
    watch: './img/P_HR_White.png',
    secondStyle: './img/P_HR_Lilac.png',
    thirdStyle: './img/P_HR_Black.png',
    animation: null,
    firstColor: 'content__change-color-btn-first-hr',
    secondColor: 'content__change-color-btn-second-hr',
    thirdColor: 'content__change-color-btn-third-hr',
    name: 'fitbit inspire <p class="content__sign-type">hr</p>',
    priceEuro: 99,
    priceCents: 95,
    information: '',
  },
]